/*********************************************************************************************************************
    ClassName AutoConvertLeadsTest
    Purpose: This is a test class used to test the AutoConvertLeads functionality.
    AUTHOR : G Soundarya
    Date : 08-July-2023
********************************************************************************************************************/
@isTest
public with sharing class AutoConvertLeadsTest {
    public AutoConvertLeadsTest() {    }

    // @isTest
    // private static void convertTest(){

    //     list<id> data = new list<id>{'00Q2z000002KOV5EAO'};

    //     test.startTest();
    //     AutoConvertLeads.assignLeads(data);
    //     test.stopTest();
    // }
}