/*********************************************************************************************************************
    ClassName nestedLookupTest
    Purpose: This is a test class used to test the nestedLookup functionality.
    AUTHOR : G Soundarya
    Date : 08-July-2023
********************************************************************************************************************/
@isTest
public with sharing class ProjectWrapperTest {
    public ProjectWrapperTest() {    }

    @istest
    private static void projwrap(){

        test.startTest();

        //ProjectWrapper.projectGroupName test = new ProjectWrapper.projectGroupName('hello');
        // data.projectName='hello';
        // data.projectId = '11231233';
        // data.projectGroupId = '23123123';
        // data.projectStatus = 'pending';
        // data.organisationName = 'wipro';
        test.stopTest();
    }
}